name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # This command forces our 'main' branch to become the 'main' branch on Hugging Face
          git push --force https://Elijah04:$HF_TOKEN@huggingface.co/spaces/Elijah04/Elijah-AI main:refs/heads/main
